#include "composer.h"
#include <random>

namespace lambda
{
  String Composer::generateArtistName(const size_t& hash) const
  {
    Vector<String> first_name  = {
      "Bon",
      "Def",
      "Duran",
      "Michael",
      "Prince",
      "Hall",
      "Guns",
      "Madonna",
      "Run",
      "AC/DC",
      "Journey",
      "Whitney",
      "U2",
      "The",
      "Van",
      "INXS",
      "Whitesnake",
      "Dexy's",
      "Cyndi",
      "Rick",
      "Michael",
      "The",
      "Cyndi",
      "A-Ha",
      "The",
      "Guns",
      "Kajagoogoo",
      "Wham!",
      "Talking",
      "Pat",
      "Queen",
      "Night",
      "Soft",
      "Poison",
      "Phil",
      "Tommy",
      "Aerosmith",
      "U2",
      "Modern",
      "The",
      "Mötley",
      "The",
      "ABC",
      "Bananarama",
      "Janet",
      "The",
      "Twisted",
      "Bruce",
      "Beastie",
      "Eurythmics",
      "Ratt",
      "Dead or",
      "Billy",
      "Salt-N-Pepa",
      "A Flock of",
      "Bonnie",
      "Toni",
      "Culture",
      "John",
      "Young",
      "Styx",
      "Berlin",
      "Devo",
      "Paula",
      "Foreigner",
      "Depeche",
      "REO",
      "Public",
      "R.E.M.",
      "Joan",
      "The",
      "Rick",
      "The",
      "Nena",
      "George",
      "Prince",
      "Thomas",
      "New",
      "Blondie",
      "Human",
      "Rob",
      "DJ",
      "Cameo",
      "Squeeze",
      "Prince",
      "Lionel",
      "Robert",
      "Bow",
      "Falco",
      "Chaka",
      "The",
      "Tone-Loc",
      "Katrina",
      "The New Kids",
      "Gary",
      "The Rolling",
      "Debbie",
      "Men at",
      "The",
      "Bobby",
      "Wang",
      "Loverboy"
    };
    Vector<String> second_name = {
      "Jovi",
      "Leppard",
      "Duran",
      "Jackson",
      "",
      "& Oates",
      "N' Roses",
      "",
      "DMC",
      "",
      "",
      "Houston",
      "",
      "Bangles",
      "Halen",
      "",
      "",
      "Midnight Runners",
      "Lauper",
      "Springfield",
      "Jackson",
      "Cure",
      "Lauper",
      "",
      "Go-Go's",
      "N' Roses",
      "",
      "",
      "Heads",
      "Benatar",
      "David Bowie",
      "Ranger",
      "Cell",
      "",
      "Collins",
      "Tutone",
      "",
      "",
      "English",
      "B-52's",
      "Crüe",
      "Clash",
      "",
      "",
      "Jackson",
      "Police",
      "Sister",
      "Springsteen",
      "Boys",
      "",
      "",
      "Alive",
      "Idol",
      "",
      "Seagulls",
      "Tyler",
      "Basil",
      "Club",
      "Mellencamp",
      "M.C.",
      "",
      "",
      "",
      "Abdul",
      "",
      "Mode",
      "Speedwagon",
      "Enemy",
      "",
      "Jett",
      "Blackhearts",
      "James",
      "Fixx",
      "",
      "Michael",
      "",
      "Dolby",
      "Edition",
      "",
      "League",
      "Base",
      "E-Z", "Rock",
      "",
      "",
      "",
      "Richie",
      "Palmer",
      "Wow Wow",
      "",
      "Khan",
      "Pretenders",
      "",
      "and the Waves",
      "on the Block",
      "Numan",
      "Stones",
      "Gibson",
      "Work",
      "Romantics",
      "Brown",
      "Chung",
      ""
    };

    std::mt19937 mt((unsigned int)hash);
    std::uniform_int_distribution<int> dist(0, 102);
    String first  = first_name.at(dist(mt));
    String second = second_name.at(dist(mt));

    return first + (second.empty() ? "" : " ") + second;
  }

  String Composer::generateSongName(const size_t& hash) const
  {
    Vector<String> first_name  = {
      "Livin' on a",
      "Pour Some",
      "Hungry Like",
      "Billie",
      "When",
      "I Can't Go For That",
      "Sweet Child",
      "Like a",
      "Walk",
      "You Shook Me",
      "Don't Stop",
      "How Will",
      "With Or",
      "Walk Like",
      "Jump",
      "Need You",
      "Here I Go",
      "Come On",
      "Time",
      "Jessie's",
      "Beat",
      "Just",
      "Girls Just Want to",
      "Take On",
      "Our Lips Are",
      "Welcome to",
      "Too",
      "Wake Me Up",
      "Burning Down",
      "Love is",
      "Under",
      "Sister",
      "Tainted",
      "Every Rose Has",
      "In the",
      "867-5309",
      "Janie's Got",
      "Pride",
      "I Melt",
      "Love",
      "Dr.",
      "London",
      "Look of",
      "Cruel",
      "Nasty",
      "Every Breath",
      "We're Not Gonna",
      "Born in",
      "Fight For",
      "Sweet Dreams",
      "Round and",
      "You Spin Me Round",
      "White",
      "Push",
      "I Ran",
      "Total Eclipse of",
      "Mickey",
      "Do You Really Want to",
      "Jack",
      "Bust",
      "Mr.",
      "Take My",
      "Whip",
      "Straight",
      "I Want to Know",
      "Just Can't Get",
      "Keep On Loving",
      "Fight the",
      "It's the End of",
      "I Love",
      "Super",
      "One Thing Leads to",
      "99",
      "Faith",
      "Little Red",
      "She Blinded Me With",
      "Candy",
      "Call",
      "Don't You Want",
      "It Takes",
      "Word",
      "Tempted",
      "Kiss",
      "All Night Long",
      "Addicted to",
      "I Want",
      "Rock Me",
      "Ain't",
      "Brass in",
      "Wild",
      "Walking On",
      "You Got It",
      "Cars",
      "Start Me",
      "Only in My",
      "Down",
      "What I Like About",
      "My",
      "Everybody Have",
      "Working for",
    };
    Vector<String> second_name = {
      "Prayer",
      "Sugar On Me",
      "the Wolf",
      "Jean",
      "Doves Cry",
      "(No Can Do)",
      "O' Mine",
      "Virgin",
      "This Way",
      "All Night Long",
      "Believing",
      "I Know",
      "Without You",
      "an Egyptian",
      "",
      "Tonight",
      "Again",
      "Eileen",
      "After Time",
      "Girl",
      "It",
      "Like Heaven",
      "Have Fun",
      "Me",
      "Sealed",
      "the Jungle",
      "Shy",
      "Before You Go-Go",
      "the House",
      "a Battlefield",
      "Pressure",
      "Christian",
      "Love",
      "It's Thorn",
      "Air Tonight",
      "Jenny",
      "a Gun",
      "(In the Name of Love)",
      "With You",
      "Shack",
      "Feelgood",
      "Calling",
      "Love",
      "Summer",
      "",
      "You Take",
      "Take It",
      "the U.S.A.",
      "Your Right",
      "(Are Made of This)",
      "Round",
      "(Like A Record)",
      "Wedding",
      "It",
      "(So Far Away)",
      "the Heart",
      "",
      "Hurt Me",
      "& Diane",
      "a Move",
      "Roboto",
      "Breath Away",
      "It",
      "Up",
      "What Love Is",
      "Enough",
      "You",
      "Power",
      "the World as We Know It (And I Feel Fine)",
      "Rock N' Roll",
      "Freak",
      "Another",
      "Luftballons",
      "",
      "Corvette",
      "Science",
      "Girl",
      "Me",
      "Me?",
      "Two",
      "Up!",
      "",
      "",
      "(All Night)",
      "Love",
      "Candy",
      "Amadeus",
      "Nobody",
      "Pocket",
      "Thing",
      "Sunshine",
      "(The Right Stuff)",
      "",
      "Up",
      "Dreams",
      "Under",
      "You",
      "Perogative",
      "Fun Tonight",
      "the Weekend",
    };

    std::mt19937 mt((unsigned int)hash);
    std::uniform_int_distribution<int> dist(0, 100);
    String first  = first_name.at(dist(mt));
    String second = second_name.at(dist(mt));

    return first + (second.empty() ? "" : " ") + second;
  }
}